# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  docker: circleci/docker@0.6.0
# Orchestrate or schedule a set of jobs
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.5
    steps:
      - setup_remote_docker
      - checkout
      - docker/build:
          image: eswdd-test/docker-test
      - run: ls -la
      - run: git clone https://github.com/eswdd-test/github-app-authenticator
      - run:
          command: go build -o github-app-authenticator *.go
          working_directory: github-app-authenticator
      - run: github-app-authenticator/github-app-authenticator --installation-id=${GITHUB_INSTALL_ID} --application-id=${GITHUB_APP_ID} --private-key=github.pem > github.token
      - run: export GITHUB_TOKEN=`cat github.token`
      - run: ls -la
      
      
