# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  docker: circleci/docker@0.6.0
# Orchestrate or schedule a set of jobs
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.5
    environment:
      DOCKER_USER: docker-test-publisher
      SOURCE_IMAGE: eswdd-test/docker-test
      IMAGE_NAME: docker.pkg.github.com/eswdd-test/docker-test/autobuild
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Docker build
          command: |
            set -x
            extra=
            if [[ "$CIRCLE_TAG" != "" ]]; then
              branch=$CIRCLE_TAG
            else
              branch=$CIRCLE_BRANCH
            fi
            docker build -t $SOURCE_IMAGE:$branch --build-arg GIT_REVISION="$CIRCLE_SHA1" --build-arg GIT_BRANCH="$branch" --build-arg BUILD_USER="circleci" .      - run: ls -la
      - run:
          name: Push autobuild Docker image
          command: |
            docker login --username "$DOCKER_HUB_USER" --password "$DOCKER_HUB_PASSWORD"
            set -x
            if [[ $CIRCLE_TAG != "" ]]; then
              branch=$CIRCLE_TAG
            else
              branch=$CIRCLE_BRANCH
            fi
            if [[ $CIRCLE_TAG == "" ]] && [[ $CIRCLE_BRANCH != "master" ]]; then
              echo "Not on a tag or master, skipped."
              exit 0
            fi
            docker tag $SOURCE_IMAGE:$branch $IMAGE_NAME:$branch
            docker push $IMAGE_NAME:$branch
      
      
